version: '3.8'

services:
  mongo:
    image: docker.io/library/mongo:7
    container_name: viet_future_mongo
    ports:
      - "27017:27017"
    env_file:
      - ./Backend/.env
    environment:
      - MONGO_INITDB_DATABASE=viet_future
    volumes:
      - mongo_data:/data/db

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: viet_future_backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes: 
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=development

volumes:
  mongo_data: